/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdjectivesRouteImport } from './routes/adjectives'
import { Route as AlphabetRouteImport } from './routes/alphabet'
import { Route as BasicsRouteImport } from './routes/basics'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as GrammarRouteImport } from './routes/grammar'
import { Route as HarmonyRouteImport } from './routes/harmony'
import { Route as LabRouteImport } from './routes/lab'
import { Route as PhrasesRouteImport } from './routes/phrases'
import { Route as PossessionRouteImport } from './routes/possession'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PronounsRouteImport } from './routes/pronouns'
import { Route as SupportRouteImport } from './routes/support'
import { Route as VerbsRouteImport } from './routes/verbs'
import { Route as WordBuildingRouteImport } from './routes/word-building'
import { Route as CasesSlugRouteImport } from './routes/cases.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdjectivesRoute = AdjectivesRouteImport.update({
  id: '/adjectives',
  path: '/adjectives',
  getParentRoute: () => rootRouteImport,
} as any)
const AlphabetRoute = AlphabetRouteImport.update({
  id: '/alphabet',
  path: '/alphabet',
  getParentRoute: () => rootRouteImport,
} as any)
const BasicsRoute = BasicsRouteImport.update({
  id: '/basics',
  path: '/basics',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const GrammarRoute = GrammarRouteImport.update({
  id: '/grammar',
  path: '/grammar',
  getParentRoute: () => rootRouteImport,
} as any)
const HarmonyRoute = HarmonyRouteImport.update({
  id: '/harmony',
  path: '/harmony',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const PhrasesRoute = PhrasesRouteImport.update({
  id: '/phrases',
  path: '/phrases',
  getParentRoute: () => rootRouteImport,
} as any)
const PossessionRoute = PossessionRouteImport.update({
  id: '/possession',
  path: '/possession',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PronounsRoute = PronounsRouteImport.update({
  id: '/pronouns',
  path: '/pronouns',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const VerbsRoute = VerbsRouteImport.update({
  id: '/verbs',
  path: '/verbs',
  getParentRoute: () => rootRouteImport,
} as any)
const WordBuildingRoute = WordBuildingRouteImport.update({
  id: '/word-building',
  path: '/word-building',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesSlugRoute = CasesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CasesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/adjectives': typeof AdjectivesRoute
  '/alphabet': typeof AlphabetRoute
  '/basics': typeof BasicsRoute
  '/cases': typeof CasesRouteWithChildren
  '/grammar': typeof GrammarRoute
  '/harmony': typeof HarmonyRoute
  '/lab': typeof LabRoute
  '/phrases': typeof PhrasesRoute
  '/possession': typeof PossessionRoute
  '/practice': typeof PracticeRoute
  '/privacy': typeof PrivacyRoute
  '/pronouns': typeof PronounsRoute
  '/support': typeof SupportRoute
  '/verbs': typeof VerbsRoute
  '/word-building': typeof WordBuildingRoute
  '/cases/$slug': typeof CasesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/adjectives': typeof AdjectivesRoute
  '/alphabet': typeof AlphabetRoute
  '/basics': typeof BasicsRoute
  '/cases': typeof CasesRouteWithChildren
  '/grammar': typeof GrammarRoute
  '/harmony': typeof HarmonyRoute
  '/lab': typeof LabRoute
  '/phrases': typeof PhrasesRoute
  '/possession': typeof PossessionRoute
  '/practice': typeof PracticeRoute
  '/privacy': typeof PrivacyRoute
  '/pronouns': typeof PronounsRoute
  '/support': typeof SupportRoute
  '/verbs': typeof VerbsRoute
  '/word-building': typeof WordBuildingRoute
  '/cases/$slug': typeof CasesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/adjectives': typeof AdjectivesRoute
  '/alphabet': typeof AlphabetRoute
  '/basics': typeof BasicsRoute
  '/cases': typeof CasesRouteWithChildren
  '/grammar': typeof GrammarRoute
  '/harmony': typeof HarmonyRoute
  '/lab': typeof LabRoute
  '/phrases': typeof PhrasesRoute
  '/possession': typeof PossessionRoute
  '/practice': typeof PracticeRoute
  '/privacy': typeof PrivacyRoute
  '/pronouns': typeof PronounsRoute
  '/support': typeof SupportRoute
  '/verbs': typeof VerbsRoute
  '/word-building': typeof WordBuildingRoute
  '/cases/$slug': typeof CasesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/adjectives'
    | '/alphabet'
    | '/basics'
    | '/cases'
    | '/grammar'
    | '/harmony'
    | '/lab'
    | '/phrases'
    | '/possession'
    | '/practice'
    | '/privacy'
    | '/pronouns'
    | '/support'
    | '/verbs'
    | '/word-building'
    | '/cases/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/adjectives'
    | '/alphabet'
    | '/basics'
    | '/cases'
    | '/grammar'
    | '/harmony'
    | '/lab'
    | '/phrases'
    | '/possession'
    | '/practice'
    | '/privacy'
    | '/pronouns'
    | '/support'
    | '/verbs'
    | '/word-building'
    | '/cases/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/adjectives'
    | '/alphabet'
    | '/basics'
    | '/cases'
    | '/grammar'
    | '/harmony'
    | '/lab'
    | '/phrases'
    | '/possession'
    | '/practice'
    | '/privacy'
    | '/pronouns'
    | '/support'
    | '/verbs'
    | '/word-building'
    | '/cases/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdjectivesRoute: typeof AdjectivesRoute
  AlphabetRoute: typeof AlphabetRoute
  BasicsRoute: typeof BasicsRoute
  CasesRoute: typeof CasesRouteWithChildren
  GrammarRoute: typeof GrammarRoute
  HarmonyRoute: typeof HarmonyRoute
  LabRoute: typeof LabRoute
  PhrasesRoute: typeof PhrasesRoute
  PossessionRoute: typeof PossessionRoute
  PracticeRoute: typeof PracticeRoute
  PrivacyRoute: typeof PrivacyRoute
  PronounsRoute: typeof PronounsRoute
  SupportRoute: typeof SupportRoute
  VerbsRoute: typeof VerbsRoute
  WordBuildingRoute: typeof WordBuildingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adjectives': {
      id: '/adjectives'
      path: '/adjectives'
      fullPath: '/adjectives'
      preLoaderRoute: typeof AdjectivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alphabet': {
      id: '/alphabet'
      path: '/alphabet'
      fullPath: '/alphabet'
      preLoaderRoute: typeof AlphabetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/basics': {
      id: '/basics'
      path: '/basics'
      fullPath: '/basics'
      preLoaderRoute: typeof BasicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grammar': {
      id: '/grammar'
      path: '/grammar'
      fullPath: '/grammar'
      preLoaderRoute: typeof GrammarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/harmony': {
      id: '/harmony'
      path: '/harmony'
      fullPath: '/harmony'
      preLoaderRoute: typeof HarmonyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phrases': {
      id: '/phrases'
      path: '/phrases'
      fullPath: '/phrases'
      preLoaderRoute: typeof PhrasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/possession': {
      id: '/possession'
      path: '/possession'
      fullPath: '/possession'
      preLoaderRoute: typeof PossessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pronouns': {
      id: '/pronouns'
      path: '/pronouns'
      fullPath: '/pronouns'
      preLoaderRoute: typeof PronounsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verbs': {
      id: '/verbs'
      path: '/verbs'
      fullPath: '/verbs'
      preLoaderRoute: typeof VerbsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/word-building': {
      id: '/word-building'
      path: '/word-building'
      fullPath: '/word-building'
      preLoaderRoute: typeof WordBuildingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$slug': {
      id: '/cases/$slug'
      path: '/$slug'
      fullPath: '/cases/$slug'
      preLoaderRoute: typeof CasesSlugRouteImport
      parentRoute: typeof CasesRoute
    }
  }
}

interface CasesRouteChildren {
  CasesSlugRoute: typeof CasesSlugRoute
}

const CasesRouteChildren: CasesRouteChildren = {
  CasesSlugRoute: CasesSlugRoute,
}

const CasesRouteWithChildren = CasesRoute._addFileChildren(CasesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdjectivesRoute: AdjectivesRoute,
  AlphabetRoute: AlphabetRoute,
  BasicsRoute: BasicsRoute,
  CasesRoute: CasesRouteWithChildren,
  GrammarRoute: GrammarRoute,
  HarmonyRoute: HarmonyRoute,
  LabRoute: LabRoute,
  PhrasesRoute: PhrasesRoute,
  PossessionRoute: PossessionRoute,
  PracticeRoute: PracticeRoute,
  PrivacyRoute: PrivacyRoute,
  PronounsRoute: PronounsRoute,
  SupportRoute: SupportRoute,
  VerbsRoute: VerbsRoute,
  WordBuildingRoute: WordBuildingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
